import { useState, useEffect } from 'react';
import Script from 'next/script';

export default function KeyGen() {
  const [keys, setKeys] = useState({ publicKey: '', privateKey: '' });
  const [status, setStatus] = useState('Waiting for C-WASM...');
  const [wasmReady, setWasmReady] = useState(false);

  // Helper: Convert C-memory (Uint8Array) to Hex String
  const toHex = (arr) => 
    Array.from(arr).map(b => b.toString(16).padStart(2, '0')).join('').toUpperCase();

  return (
    <div className="p-8 font-sans max-w-4xl mx-auto">
      {/* 1. LOAD THE COMPILED C CODE */}
      <Script 
        src="/wasm_keygen.js" 
        onLoad={() => {
          // Wait for Emscripten to be ready
          window.Module.onRuntimeInitialized = () => {
            setWasmReady(true);
            setStatus('Ready. Loaded keygen.c via WebAssembly!');
          };
        }}
      />

      <h1 className="text-2xl font-bold mb-6 text-green-700">PQC Key Generator (C + WASM)</h1>
      <p className="mb-6 text-gray-600">
        This page runs your <b>C code</b> directly in the browser using WebAssembly.
      </p>

      <button 
        disabled={!wasmReady}
        onClick={() => {
          try {
            const Module = window.Module;
            setStatus('Allocating memory in C...');

            // A. Get sizes from C
            const pkSize = Module._get_pubkey_size(); // 800
            const skSize = Module._get_privkey_size(); // 1632

            // B. Allocate memory in the WASM Heap
            const pkPtr = Module._malloc(pkSize);
            const skPtr = Module._malloc(skSize);

            // C. Run the C function!
            Module._generate_kyber_keys(pkPtr, skPtr);

            // D. Read results back from memory
            const pkBytes = new Uint8Array(Module.HEAPU8.buffer, pkPtr, pkSize);
            const skBytes = new Uint8Array(Module.HEAPU8.buffer, skPtr, skSize);

            // E. Display them
            setKeys({
              publicKey: toHex(pkBytes),
              privateKey: toHex(skBytes)
            });

            // F. Clean up C memory
            Module._free(pkPtr);
            Module._free(skPtr);

            setStatus('Success! Keys generated by liboqs (C).');
          } catch (e) {
            setStatus('Error: ' + e.message);
          }
        }}
        className={`px-6 py-2 rounded font-bold mb-6 text-white ${wasmReady ? 'bg-green-600 hover:bg-green-700' : 'bg-gray-400'}`}
      >
        {wasmReady ? "Generate Keys (Run C Code)" : "Loading WASM..."}
      </button>

      <p className="font-bold mb-4">{status}</p>

      <div className="space-y-6">
        <div>
          <h3 className="font-bold text-lg">Public Key</h3>
          <textarea className="w-full h-32 p-2 border text-xs font-mono" readOnly value={keys.publicKey} />
        </div>

        <div>
          <h3 className="font-bold text-lg text-red-600">Private Key</h3>
          <textarea className="w-full h-32 p-2 border text-xs font-mono" readOnly value={keys.privateKey} />
        </div>
      </div>
    </div>
  );
}