import { useEffect, useState } from 'react';

import { generateKeyPair, getWasmModule } from '../utils/crypto';

export default function KeyGen() {
  const [keys, setKeys] = useState({ publicKey: '', privateKey: '' });
  const [status, setStatus] = useState('Loading the post-quantum module...');
  const [wasmReady, setWasmReady] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  // The module is loaded once in _document. Waiting on the shared readiness
  // promise avoids the previous approach of mounting a second copy of the
  // script and assigning Module.onRuntimeInitialized, which never fired.
  useEffect(() => {
    let cancelled = false;

    getWasmModule().then(
      () => {
        if (cancelled) return;
        setWasmReady(true);
        setStatus('Ready. Loaded keygen.c via WebAssembly.');
      },
      (error) => {
        if (cancelled) return;
        setStatus(`Error: ${error.message}`);
      }
    );

    return () => {
      cancelled = true;
    };
  }, []);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setStatus('Generating keypair...');
    try {
      setKeys(await generateKeyPair());
      setStatus('Success! Keys generated by liboqs (C).');
    } catch (error) {
      setStatus(`Error: ${error.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const canGenerate = wasmReady && !isGenerating;

  return (
    <div className="p-8 font-sans max-w-4xl mx-auto">
      <h1 className="text-2xl font-bold mb-6 text-green-700">PQC Key Generator (C + WASM)</h1>
      <p className="mb-6 text-gray-600">
        This page runs your <b>C code</b> directly in the browser using WebAssembly.
      </p>

      <button
        disabled={!canGenerate}
        onClick={handleGenerate}
        className={`px-6 py-2 rounded font-bold mb-6 text-white ${
          canGenerate ? 'bg-green-600 hover:bg-green-700' : 'bg-gray-400'
        }`}
      >
        {wasmReady ? 'Generate Keys (Run C Code)' : 'Loading WASM...'}
      </button>

      <p className="font-bold mb-4">{status}</p>

      <div className="space-y-6">
        <div>
          <h3 className="font-bold text-lg">Public Key</h3>
          <textarea
            className="w-full h-32 p-2 border text-xs font-mono"
            readOnly
            value={keys.publicKey}
          />
        </div>

        <div>
          <h3 className="font-bold text-lg text-red-600">Private Key</h3>
          <p className="text-xs text-gray-500 mb-1">
            Save this somewhere safe. It never leaves your browser and cannot be recovered.
          </p>
          <textarea
            className="w-full h-32 p-2 border text-xs font-mono"
            readOnly
            value={keys.privateKey}
          />
        </div>
      </div>
    </div>
  );
}
